spring:
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: "jdbc:mysql://mysql:3306/test"
     username: root
     password: rathod
  jpa:
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     hibernate.ddl-auto: create
     generate-ddl: true
     show-sql: true
