pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
        }
    }
    stages {
	stage('SCM') {
	    steps {
		git url: "https://github.com/vickyrathod/khaopiobackend.git"
	    }
	}
        stage('Build') {
            steps {
               sh 'mvn clean package docker:build'
            }
        }
        stage('publish') {
            steps {
                sh 'docker push vicky123/catalogservices:${env.BUILD_ID}'
            }
        }
    }
}
